"""add rolex to user

Revision ID: 04ad7038df6c
Revises: b7f64df64f0e
Create Date: 2026-03-30 21:39:02.445864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 



# revision identifiers, used by Alembic.
revision: str = '04ad7038df6c'
down_revision: Union[str, Sequence[str], None] = 'b7f64df64f0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
